services:
#  api:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    container_name: cinema_api
#    env_file:
#      - ../.env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#      - redis
#    volumes:
#      - ../src:/app/src

  postgres:
    image: postgres:15
    container_name: cinema_postgres
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"

#  redis:
#    image: redis:7
#    container_name: cinema_redis
#    ports:
#      - "6379:6379"
#
#  celery:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    command: celery -A src.celery_app worker -l info
#    env_file:
#      - ../.env
#    depends_on:
#      - redis
#      - postgres
#
#  celery-beat:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    command: celery -A src.celery_app beat -l info
#    env_file:
#      - ../.env
#    depends_on:
#      - redis
